### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by MK85Pilot** [stmtc233/ipv6-proxy-pool#1]
例如ipv6.ip.sb解析地址时会有点问题
Error connecting to destination: address 2a09:0:13::9:80: too many colons in address

// 修复建立到目标服务器的连接
destConn, err := zdipfw("tcp6", fmt.Sprintf("[%s]:%d", destAddr, destPort), ipv6Addresses[counter.Increment()])

//destConn, err := zdipfw("tcp6", fmt.Sprintf("%s:%d", destAddr, destPort), ipv6Addresses[counter.Increment()])

**Comment by stmtc233** [comment]
已知晓该问题 会在下个版本修复
